Replace mute/unmute checkmenuitem with imagemenuitem
mate-desktop/mate-media pull request #175
Opened 2021-07-29 12:34 UTC by FreaxMATE

This replaces the Mute checkmenuitem with a imagemenuitem of mate-volume-status-icon to make it coherent to the mate-volume-applet.

before:
![Screenshot at 2021-07-29 14-24-16](https://user-images.githubusercontent.com/49864414/127492285-217158e9-a249-4b7a-813d-9805a5b9f52b.png)
after:
![Peek 2021-07-29 14-27](https://user-images.githubusercontent.com/49864414/127492358-fea12f5b-3e9d-477a-b821-6a6e4d095779.gif)

It also shows whether you are mutin orunmuting the input or output.

2021-07-29 15:49 UTC, zhuyaliang commented on mate-volume-control/gvc-stream-status-icon.c
> +                        image = gtk_image_new_from_icon_name("audio-volume-medium", GTK_ICON_SIZE_MENU);
It should be used here ```icon->priv->icon_ names[icon->priv->current_ icon]```
Maybe we don't have to judge here
```
g_strdup_printf （"Unmute %s",icon->priv->display_name）
```

2021-07-29 15:49 UTC, zhuyaliang commented on mate-volume-control/gvc-stream-status-icon.c
> +                        item = gtk_image_menu_item_new_with_mnemonic(_("_Unmute Output"));
It should be used here ```icon->priv->icon_ names[icon->priv->current_ icon]```
Maybe we don't have to judge here
```
g_strdup_printf （"Unmute %s",icon->priv->display_name）
```

2021-07-29 20:20 UTC, FreaxMATE commented on mate-volume-control/gvc-stream-status-icon.c
> +                        item = gtk_image_menu_item_new_with_mnemonic(_("_Unmute Output"));
Sorry I do not really understand what exactly you mean. Could you explain it what could be improved?

2021-07-30 20:41 UTC, lukefromdc reviewed
This does function as currently written-and it does have the advantage of making the behavior of the status icon more consistant with that of the newer volume control panel applet.

2021-07-31 03:13 UTC, zhuyaliang commented on mate-volume-control/gvc-stream-status-icon.c
> +                        item = gtk_image_menu_item_new_with_mnemonic(_("_Unmute Output"));
There are four states
```
static const gchar *icon_names_output[] = {
        "audio-volume-muted",
        "audio-volume-low",
        "audio-volume-medium",
        "audio-volume-high",
        NULL
};

static const gchar *icon_names_input[] = {
        "audio-input-microphone-muted",
        "audio-input-microphone-low",
        "audio-input-microphone-medium",
        "audio-input-microphone-high",
        NULL
};
```
Like this
```
        if (mate_mixer_stream_control_get_mute (icon->priv->control))
        {
                label = g_strdup_printf ("Unmute %s", icon->priv->display_name);
        }
        else
        {
                label = g_strdup_printf ("Mute %s", icon->priv->display_name);
        }
        item = gtk_image_menu_item_new_with_mnemonic(label);
        image = gtk_image_new_from_icon_name(icon->priv->icon_names[icon->priv->current_icon], GTK_ICON_SIZE_MENU);
```
But I didn't test it，I'll tell you later whether the change was successful

2021-07-31 14:02 UTC, zhuyaliang commented on mate-volume-control/gvc-stream-status-icon.c
> +                        item = gtk_image_menu_item_new_with_mnemonic(_("_Unmute Output"));
After testing, the effect is good

2021-07-31 16:34 UTC, FreaxMATE commented on mate-volume-control/gvc-stream-status-icon.c
> +                        item = gtk_image_menu_item_new_with_mnemonic(_("_Unmute Output"));
Thanks man!

2021-08-01 04:33 UTC, zhuyaliang approved these changes

2021-08-01 13:55 UTC, raveit65 requested changes
Why not testing building?
```
make[3]: *** [Makefile:770: mate_volume_control_status_icon-gvc-stream-status-icon.o] Error 1
make[3]: Leaving directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-media-dist/mate-volume-control'
make[2]: *** [Makefile:519: all] Error 2
make[2]: Leaving directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-media-dist/mate-volume-control'
make[1]: *** [Makefile:467: all-recursive] Error 1
make[1]: Leaving directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-media-dist'
make: *** [Makefile:399: all] Error 2
```

2021-08-01 18:40 UTC, lukefromdc commented
What went different? My build finished fine.We need the linea above where the cut and pasted error message text starts to see what failed.

On 8/1/2021 at 9:55 AM, "raveit65" ***@***.***> wrote:
>
***@***.*** requested changes on this pull request.
>
>Why not testing building?
>```
>make[3]: *** [Makefile:770: mate_volume_control_status_icon-gvc-
>stream-status-icon.o] Error 1
>make[3]: Leaving directory '/media/Data/Programme/Linux/Mate-
>Desktop/git-version/github-matedesktop/mate-media-dist/mate-volume-
>control'
>make[2]: *** [Makefile:519: all] Error 2
>make[2]: Leaving directory '/media/Data/Programme/Linux/Mate-
>Desktop/git-version/github-matedesktop/mate-media-dist/mate-volume-
>control'
>make[1]: *** [Makefile:467: all-recursive] Error 1
>make[1]: Leaving directory '/media/Data/Programme/Linux/Mate-
>Desktop/git-version/github-matedesktop/mate-media-dist'
>make: *** [Makefile:399: all] Error 2
>```
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/mate-desktop/mate-
>media/pull/175#pullrequestreview-719665292

2021-08-01 19:05 UTC, raveit65 commented
Full log with errors:
```
make[3]: Entering directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-media-dist/mate-volume-control'
  CC       mate_volume_control_status_icon-gvc-stream-status-icon.o
gvc-stream-status-icon.c: In function 'popup_dock':
gvc-stream-status-icon.c:74:9: warning: 'gtk_status_icon_get_screen' is deprecated [-Wdeprecated-declarations]
   74 |         screen = gtk_status_icon_get_screen (GTK_STATUS_ICON (icon));
      |         ^~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:275,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:131:23: note: declared here
  131 | GdkScreen            *gtk_status_icon_get_screen         (GtkStatusIcon      *status_icon);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-stream-status-icon.c:76:9: warning: 'gtk_status_icon_get_geometry' is deprecated [-Wdeprecated-declarations]
   76 |         if (gtk_status_icon_get_geometry (GTK_STATUS_ICON (icon),
      |         ^~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:275,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:166:23: note: declared here
  166 | gboolean              gtk_status_icon_get_geometry       (GtkStatusIcon      *status_icon,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-stream-status-icon.c: In function 'on_status_icon_popup_menu':
gvc-stream-status-icon.c:235:17: error: 'label' undeclared (first use in this function)
  235 |                 label = g_strdup_printf ("Unmute %s", icon->priv->display_name);
      |                 ^~~~~
gvc-stream-status-icon.c:235:17: note: each undeclared identifier is reported only once for each function it appears in
gvc-stream-status-icon.c:241:9: warning: 'gtk_image_menu_item_new_with_mnemonic' is deprecated: Use 'gtk_menu_item_new_with_mnemonic' instead [-Wdeprecated-declarations]
  241 |         item = gtk_image_menu_item_new_with_mnemonic(label);
      |         ^~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:269,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkimagemenuitem.h:82:12: note: declared here
   82 | GtkWidget* gtk_image_menu_item_new_with_mnemonic (const gchar      *label);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-stream-status-icon.c:244:9: warning: 'gtk_image_menu_item_set_image' is deprecated [-Wdeprecated-declarations]
  244 |         gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (item), image);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:269,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkimagemenuitem.h:92:12: note: declared here
   92 | void       gtk_image_menu_item_set_image         (GtkImageMenuItem *image_menu_item,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-stream-status-icon.c:244:9: warning: 'gtk_image_menu_item_get_type' is deprecated: Use 'gtk_menu_item_get_type' instead [-Wdeprecated-declarations]
  244 |         gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (item), image);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:269,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkimagemenuitem.h:76:12: note: declared here
   76 | GType      gtk_image_menu_item_get_type          (void) G_GNUC_CONST;
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-stream-status-icon.c:252:9: warning: 'gtk_image_menu_item_new_with_mnemonic' is deprecated: Use 'gtk_menu_item_new_with_mnemonic' instead [-Wdeprecated-declarations]
  252 |         item = gtk_image_menu_item_new_with_mnemonic (_("_Sound Preferences"));
      |         ^~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:269,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkimagemenuitem.h:82:12: note: declared here
   82 | GtkWidget* gtk_image_menu_item_new_with_mnemonic (const gchar      *label);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-stream-status-icon.c:255:9: warning: 'gtk_image_menu_item_set_image' is deprecated [-Wdeprecated-declarations]
  255 |         gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (item), image);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:269,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkimagemenuitem.h:92:12: note: declared here
   92 | void       gtk_image_menu_item_set_image         (GtkImageMenuItem *image_menu_item,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-stream-status-icon.c:255:9: warning: 'gtk_image_menu_item_get_type' is deprecated: Use 'gtk_menu_item_get_type' instead [-Wdeprecated-declarations]
  255 |         gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (item), image);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:269,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkimagemenuitem.h:76:12: note: declared here
   76 | GType      gtk_image_menu_item_get_type          (void) G_GNUC_CONST;
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-stream-status-icon.c:265:9: warning: 'gtk_menu_popup' is deprecated: Use '(gtk_menu_popup_at_widget, gtk_menu_popup_at_pointer, gtk_menu_popup_at_rect)' instead [-Wdeprecated-declarations]
  265 |         gtk_menu_popup (GTK_MENU (menu),
      |         ^~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtklabel.h:34,
                 from /usr/include/gtk-3.0/gtk/gtkaccellabel.h:35,
                 from /usr/include/gtk-3.0/gtk/gtk.h:33,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/gtkmenu.h:138:12: note: declared here
  138 | void       gtk_menu_popup                 (GtkMenu             *menu,
      |            ^~~~~~~~~~~~~~
gvc-stream-status-icon.c:268:25: warning: 'gtk_status_icon_position_menu' is deprecated [-Wdeprecated-declarations]
  268 |                         gtk_status_icon_position_menu,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:275,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:160:23: note: declared here
  160 | void                  gtk_status_icon_position_menu      (GtkMenu            *menu,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-stream-status-icon.c: In function 'update_icon':
gvc-stream-status-icon.c:391:17: warning: 'gtk_status_icon_set_has_tooltip' is deprecated [-Wdeprecated-declarations]
  391 |                 gtk_status_icon_set_has_tooltip (GTK_STATUS_ICON (icon), FALSE);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:275,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:134:23: note: declared here
  134 | void                  gtk_status_icon_set_has_tooltip    (GtkStatusIcon      *status_icon,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-stream-status-icon.c:394:17: warning: 'gtk_status_icon_set_has_tooltip' is deprecated [-Wdeprecated-declarations]
  394 |                 gtk_status_icon_set_has_tooltip (GTK_STATUS_ICON (icon), TRUE);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:275,
                 from gvc-stream-status-icon.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:134:23: note: declared here
  134 | void                  gtk_status_icon_set_has_tooltip    (GtkStatusIcon      *status_icon,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-stream-status-icon.c:417:17: warning: 'gtk_status_icon_set_from_icon_name' is deprecated [-Wdeprecated-declar [...]

2021-08-01 20:29 UTC, FreaxMATE commented
Sorry I was sure I built and tested it and it worked but maybe I messed something up. There was the declaration of a `GtkWidget *label` missing but even with this it did not work as expected. The line
`image = gtk_image_new_from_icon_name(icon->priv->icon_names[icon->priv->current_icon], GTK_ICON_SIZE_MENU);`
does not work for this situation because you always want to display the opposite icon in the menu in relation to the tray icon, e.g if audio is not muted, the menu item should show "Mute Output" with the mute icon.
I corrected this and now it should work as expected.

Here is the diff of the previous state of this PR that failed building:
```diff

diff --git a/mate-volume-control/gvc-stream-status-icon.c b/mate-volume-control/gvc-stream-status-icon.c
index 0153365..aeaf268 100644
--- a/mate-volume-control/gvc-stream-status-icon.c
+++ b/mate-volume-control/gvc-stream-status-icon.c
@@ -175,11 +175,7 @@ on_status_icon_button_press (GtkStatusIcon       *status_icon,
 static void
 on_menu_mute_toggled (GtkMenuItem *item, GvcStreamStatusIcon *icon)
 {
-        gboolean is_muted;
-
-        is_muted = gtk_check_menu_item_get_active (GTK_CHECK_MENU_ITEM (item));
-
-        mate_mixer_stream_control_set_mute (icon->priv->control, is_muted);
+        mate_mixer_stream_control_set_mute (icon->priv->control, !mate_mixer_stream_control_get_mute (icon->priv->control));
 }
 
 static void
@@ -234,11 +230,20 @@ on_status_icon_popup_menu (GtkStatusIcon       *status_icon,
         gtk_style_context_add_class(context,"gnome-panel-menu-bar");
         gtk_style_context_add_class(context,"mate-panel-menu-bar");
 
-        item = gtk_check_menu_item_new_with_mnemonic (_("_Mute"));
-        gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (item),
-                                        mate_mixer_stream_control_get_mute (icon->priv->control));
+        if (mate_mixer_stream_control_get_mute (icon->priv->control))
+        {
+                label = g_strdup_printf ("Unmute %s", icon->priv->display_name);
+        }
+        else
+        {
+                label = g_strdup_printf ("Mute %s", icon->priv->display_name);
+        }
+        item = gtk_image_menu_item_new_with_mnemonic(label);
+        image = gtk_image_new_from_icon_name(icon->priv->icon_names[icon->priv->current_icon], GTK_ICON_SIZE_MENU);
+
+        gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (item), image);
         g_signal_connect (G_OBJECT (item),
-                          "toggled",
+                          "activate",
                           G_CALLBACK (on_menu_mute_toggled),
                           icon);
 
```

2021-08-02 01:12 UTC, zhuyaliang commented on mate-volume-control/gvc-stream-status-icon.c
> +        GtkWidget *label;
It should be ```g_autofree char *label = NULL```;

2021-08-03 18:24 UTC, FreaxMATE commented on mate-volume-control/gvc-stream-status-icon.c
> +        GtkWidget *label;
Thanks :)

2021-08-03 19:59 UTC, raveit65 approved these changes
LGTM,
does what it promise

2021-08-04 13:33 UTC, merged