position popup slider properly in wayland and make wayland optional
mate-desktop/mate-media pull request #196
Opened 2023-06-28 06:28 UTC by lukefromdc

Position the slider correctly in wayland (all four panel orientations tested) and allow passing --disable-wayland and --disable-in-process together for non-wayland, out of process builds

2023-06-28 06:36 UTC, lukefromdc commented
Note that all attempts to permit an in-process build without wayland support failed as efforts to pass` HAVE_WAYLAND ` twice to gvc-stream-applet-icon.c repeated failed. For some reason passing IN_PROCESS worked in its place but this couples the options together. An attempt to build in-process without wayland support fails  I an whole day of work I simply was NOT able to couple these two options together to be set by a single selector

The autotools documentation simply does not cover enough info on passing variables to preprocessing selectors in C files, and I don't have the understanding of autotools some of the others here do. I would much prefer to either have these options work independently or have one option control them both but will need help to get that done.

The reason for the second commit is complaints that the in-process applet has too many bugs elsewhere in its code that when in-process take down the whole panel. Since I don't get those bugs locally (the applet is very reliable here), I cannot fix them. This way the applet can be built in-process to support both x11 and wayland, or essentially the same as it always was for x11 only.

2023-06-28 08:02 UTC, cwendling commented
I won't be able to test the Wayland part beyond compiling, but I'll try and make a good configure check.  I think I'll go like that:
* if `--enable-wayland` is passed, require in-process (automatic)
* if `--enable-in-process` is passed, enable Wayland (automatic if available)
* if `--disable-in-process` is passed, disable Wayland (automatic)
* if there is an unsupported combination (like `--enable-wayland --disable-in-process`), fail with an error

The question might be what to default with: out-of-process like before (so no Wayland by default), or in-process?  Or in-process if Wayland is detected, but that might be a tad unexpected that having the Wayland deps changes the in-process status automatically… opinions?

2023-06-28 08:23 UTC, cwendling commented on mate-volume-control/org.mate.panel.applet.GvcAppletFactory.service
> +Exec=/usr/libexec/mate-volume-control-applet
this should use `@LOCATION@` and be a .in file

2023-06-28 08:27 UTC, raveit65 commented
IHMO, out-of-process should be default until we state the MATE-Wayland desktop as stable and ready for production.
Anyway, it's a small change to switch the default, so i don't mind very much.
I would prefer enable-in-process and disable-in-process without depending on wayland, if it's possible. This might be better for testing bugs with in-process. Not everyone has a wayland VM running.
Sadly i deleted my wayfire VM 1 or 2 yearys ago and forgot how to set up it.

2023-06-28 08:28 UTC, cwendling commented on configure.ac
> +AC_STRUCT_DIRENT_D_TYPE
what's that?  it's supposed to [check for `struct dirent::d_type`](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Particular-Structures.html), we really don't need that, do we?

2023-06-28 09:40 UTC, cwendling commented on mate-volume-control/org.mate.panel.applet.GvcAppletFactory.service
> +Exec=/usr/libexec/mate-volume-control-applet
Fix available in https://github.com/cwendling/mate-media/commits/wayland-slider

2023-06-28 09:41 UTC, cwendling commented
Here is a follow-up with the configure changes + a couple cleanups (code is better than a thousand words :smile:): https://github.com/cwendling/mate-media/commits/wayland-slider
You or I can push to this PR if you're happy with the changes.  If you're not, take what you like and leave the rest, I'm fine with anything

2023-06-28 09:42 UTC, cwendling commented on configure.ac
> +AC_STRUCT_DIRENT_D_TYPE
I got rid of it in my changes, I couldn't see its usefulness.  But I can add it back if there's a good reason still

2023-06-28 09:45 UTC, cwendling commented
> IHMO, out-of-process should be default until we state the MATE-Wayland desktop as stable and ready for production.

Makes sense to me, so that's what I did

> Anyway, it's a small change to switch the default, so i don't mind very much.

Yep, we can change the default fairly easily when we want to.

> I would prefer enable-in-process and disable-in-process without depending on wayland, if it's possible. This might be better for testing bugs with in-process. Not everyone has a wayland VM running.

Agreed, these should be independent.

2023-06-28 14:14 UTC, raveit65 commented
I tested this PR plus @cwendling improvements on top. Building with out-of-process/in-process/enable-wayland works fine. I will use in-process plus enable-wayland for better testing the applet on x11.
Now testing those options with distcheck.

2023-06-28 18:21 UTC, lukefromdc commented
I will get to work on those changes here, this sort of help is exactly what I need and I appreciate it

2023-06-28 19:27 UTC, lukefromdc commented
NICE work! I tested all four sets of possible options:` --disable-in-process `with `--enable-wayland `errored out with the message that in-process is required for wayland.
*A default build w no options built the traditional out of process applet, which won't run in wayland but won't take the panel down if it crashes in an x11 session

* A build with `--enable-in-process` set picked up my installed wayland libraries and built wayland support too, positions the popup correctly in wayland and (on my machine) runs fine on x11

* A build with `--enable-in-process` and` --disable-wayland` set (what would be built in-process if wayland libraries were not detected, I did not test removing them) runs same on x11 as above, will run on wayland but the slider popup appears in the center of the screen. This behavior allows confirming that the gtk-layer-shell library was not used and not needed for that build.

A build with just `--enable-wayland` set automatically forced in-process as well, and again worked fine on both x11 and wayland. All the wayland builds put the slider over, under, or next to the applet depending on panel position.

There is one wayland-only bug: If you put the applet on a panel and then move that panel, both the old and new anchors are set, stretching the slider across the screen.  I need to find a way to unset and reset the anchors when the panel is moved. Moving the applet within the panel does not change anchors only margins and works fine

2023-06-29 07:54 UTC, cwendling commented on configure.ac
> +dnl not, but still?
Any opinion on this?  Checking for it is a fair bit more annoying, but doable (requires an `AC_PREPROC_IFELSE` or `AC_COMPILE_IFELSE` call with the right flags)

2023-06-29 08:29 UTC, cwendling commented
I added a couple more fixes and improvements to https://github.com/cwendling/mate-media/commits/wayland-slider (one being distcheck here as well)

2023-06-29 08:31 UTC, cwendling commented
> There is one wayland-only bug: If you put the applet on a panel and then move that panel, both the old and new anchors are set, stretching the slider across the screen. I need to find a way to unset and reset the anchors when the panel is moved.

I don't know the least bit about this, so I might be completely off, but I see you only ever call `gtk_layer_set_anchor(…, TRUE)`, maybe you should call `gtk_layer_set_anchor(…, FALSE)` on the anchors you *don't* want?

2023-06-29 09:22 UTC, lukefromdc commented on configure.ac
> +dnl not, but still?
I have no idea how to do that, but if someone else suggests the code for it I'll by happy to add it in.
That said, I doubt any distro would be shipping GTK3 (which GDK builds with) built with wayland disabled, though anything is possible with some of the more obscure distros I suppose

2023-06-29 09:43 UTC, lukefromdc commented
Setting unused anchors FALSE, and also zeroing out unused margins used in other orientations worked. Now the dock renders correctly in wayland after moving the panel. Thanks again

2023-06-29 09:44 UTC, lukefromdc commented on configure.ac
> +AC_STRUCT_DIRENT_D_TYPE
Proposed changes applied

2023-06-29 09:44 UTC, lukefromdc commented on mate-volume-control/org.mate.panel.applet.GvcAppletFactory.service
> +Exec=/usr/libexec/mate-volume-control-applet
Change applied as part of your set. This really helped, thanks!

2023-06-29 09:49 UTC, cwendling commented on configure.ac
> +dnl not, but still?
It's doable but a bit annoying.  Maybe depending on pkg-config `gdk-wayland-3.0`?

2023-06-29 12:06 UTC, raveit65 commented
I squashed all improvement from @cwendling into your commit yesterday. This is currently running here.

offtopic on
2 days ago i got a panel crash during testing my new loudspeakers with my Asus Strix Raid DLX card and switching to mobo sound solution.
I got 2 stacktraces. One from the panel and one from mate-settings-daemon.
Looking in the traces it seems that pulseaudio was crashing both apps. I can post the traces if you are interested?
Sadly pulseaudio or better pipewire-pulse in fedora becomes more  unstable since pipewire is the new linux sound system. It would be better if mate-media would use pipewire directly instead of using pulseaudio which is a bit eol.
Well, that's is a future task.
What i want to say is that an external software can crash our applications including the panel when build in-process.
In this case we can nothing do but i had other issues directly related to the applet in the past.
I will take a look on them.
So i am very happy about this PR which makes it possible to use in-process when any wayland session is needed.
offtopic off

Btw. Is there any guide to set up a wayfire session with Mate?

2023-07-02 10:35 UTC, raveit65 commented on configure.ac
> +echo "    Wayland support ..........: $enable_wayland"
Only cosmetic, can the configure result  (yes) under the other?
![mate-media_configure_result](https://github.com/mate-desktop/mate-media/assets/961604/00a6cce5-e80b-4043-a5f8-0e60b2a34b81)

2023-07-02 10:58 UTC, lukefromdc commented
Of course that can be changed. I am on the road now for today but can get to that tonight or tomorrow

On 7/2/2023 at 6:35 AM, "raveit65" ***@***.***> wrote:
>
>@raveit65 commented on this pull request.
>
>
>
>> @@ -181,5 +238,7 @@ if test "x$enable_panelapplet" = "xno"; then
> else
> 	echo "    Building panel applet ......: yes"
> fi
>+echo "    Building in-process ......: $enable_in_process"
>+echo "    Wayland support ..........: $enable_wayland"
>
>Only cosmetic, can the configure result  (yes) under the other?
>![mate-media_configure_result](https://github.com/mate-
>desktop/mate-media/assets/961604/00a6cce5-e80b-4043-a5f8-
>0e60b2a34b81)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mate-desktop/mate-
>media/pull/196#pullrequestreview-1509533537
>You are receiving this because you authored the thread.
>
>Message ID: <mate-desktop/mate-
>***@***.***>

2023-07-04 07:43 UTC, cwendling commented
@raveit65 @lukefromdc the alignment should be fixed in [one of the commits](https://github.com/cwendling/mate-media/commit/7b3c66dd98fffb28b8419a8689a0f6eb874f503c) from my follow-up branch: https://github.com/cwendling/mate-media/commits/wayland-slider.  It also has more substantial improvements, like fixing distcheck.

2023-07-04 07:48 UTC, cwendling commented on configure.ac
> +dnl not, but still?
`gdk-wayland-3.0` has been added, this is thus solved (I guess)

2023-07-04 07:48 UTC, cwendling commented on configure.ac
> +echo "    Wayland support ..........: $enable_wayland"
https://github.com/cwendling/mate-media/commit/62f801f09ab5b1e54630988629608ad5293ce303

2023-07-04 07:49 UTC, cwendling commented on mate-volume-control/Makefile.am
> +		$< > $@
This breaks distcheck similar to the mate-panel case.  [Fix](https://github.com/cwendling/mate-media/commit/a32ec27c08df41c14195d1b38f18e54fe5aa978a) available in https://github.com/cwendling/mate-media/commits/wayland-slider

2023-07-04 17:48 UTC, lukefromdc commented on mate-volume-control/Makefile.am
> +		$< > $@
Your latest fixes applied, tested, and pushed. Thanks again, distcheck now works, tested that too

2023-07-04 17:51 UTC, lukefromdc commented on configure.ac
> +echo "    Wayland support ..........: $enable_wayland"
Fixed in https://github.com/mate-desktop/mate-media/pull/196/commits/761860bcd407d99576e3c35e7854ea291a20c0a2
which applies all of the latest fixes by @cwendling

2023-07-04 18:16 UTC, raveit65 approved these changes
LGTM

2023-07-04 18:17 UTC, raveit65 commented
Should we squash all commits in one with `squash and merge` option?

2023-07-04 18:55 UTC, lukefromdc commented
Yes, that's fine with me and cleans up the overall commit history

2023-07-05 07:50 UTC, cwendling requested changes

2023-07-05 07:50 UTC, cwendling commented on configure.ac
> +
wait, this should go, it makes wayland deps mandatory for any build.
If you need the version checks, move them down in `WAYLAND_DEPS`

Also, the `AC_SUBST`s are redundant and not needed

```suggestion
```

2023-07-05 07:50 UTC, cwendling commented on configure.ac
> +dnl not, but still?
these two lines can go now we check for `gdk-wayland-3.0`
```suggestion
```

2023-07-05 07:50 UTC, cwendling commented on configure.ac
> +WAYLAND_DEPS="gtk-layer-shell-0 wayland-client gdk-wayland-3.0"
So if needed, move the version checks here
```suggestion
WAYLAND_DEPS="gtk-layer-shell-0 >= $GTK_LAYER_SHELL_REQUIRED_VERSION wayland-client gdk-wayland-3.0 >= $GDK_WAYLAND_REQUIRED_VERSION"
```

2023-07-05 19:32 UTC, lukefromdc commented on configure.ac
> +dnl not, but still?
Removed

2023-07-05 19:45 UTC, lukefromdc commented on configure.ac
> +WAYLAND_DEPS="gtk-layer-shell-0 wayland-client gdk-wayland-3.0"
This works, and this is the results on Debian Unstable:
gtk-layer-shell-dev not installed, `--enable-wayland` not passed: successfull configuration and build out of process

gtk-layer-shell-dev installed, `--enable-wayland` passed: successfull configuration and build in-process w wayland support

 gtk-layer-shell-dev installed `--disable-wayland --enable-in process`  showed yes for in-process and no for wayland
and this built without issue

and

gtk-layer-shell-dev installed `--enable-wayland --disable-in process` 
errored out as intended with 
`configure: error: --enable-wayland requires --enable-in-process`

2023-07-05 19:49 UTC, lukefromdc commented on configure.ac
> +WAYLAND_DEPS="gtk-layer-shell-0 wayland-client gdk-wayland-3.0"
Thanks for catching this before it got pushed to master

2023-07-05 19:53 UTC, cwendling approved these changes
Looks good to me now

2023-07-05 19:55 UTC, lukefromdc commented on configure.ac
> +
Removed and the checks moved into the wayland block as below

2023-07-05 20:03 UTC, merged